
ignore_drive_letters:
 - C
 - D
 - Z

ignore_files_older_than: 4 weeks

# As-is, all paths under 'to' are assumed to be under the root
# of the drive matching this label. Copying from these drives is
# not currently supported.
copy_rules:
 - label: Extreme SSD
   rules:
    - from: D:\mb_team
      to: mb_team
    - from: C:\Users\user\src\cutpaste_arduino_stimuli
      glob: '*_stimuli.p'
      to: stimulus_data_files
